// Generated by CoffeeScript 1.4.0
(function() {
  var mongoose, _;

  mongoose = require("mongoose");

  _ = require('underscore');

  /*
  Provides a simple means to add tags to a schema.
  
  options:
    noDuplicates - when set to true (default) it sorts the tags and removes all duplicates.
    lowercase - when set to true (default ) automatically converts all tags to lowercase.
    sort - when set to true (default) sorts the tags. Automatically set to true when noDuplicates is set to true.
  */


  exports.tagsSimple = function(schema, options) {
    if (!options) {
      options = {};
    }
    _.defaults(options, {
      noDuplicates: true,
      lowercase: true,
      sort: true
    });
    if (options.noDuplicates) {
      options.sort = true;
    }
    schema.add({
      tags: {
        type: [String],
        "default": []
      }
    });
    return schema.pre("save", function(next) {
      if (!this.tags) {
        this.tags = [];
      }
      this.tags = _.map(this.tags, function(x) {
        if (options.lowercase) {
          return x.toLowerCase();
        }
      });
      if (options.sort && !options.noDuplicates) {
        this.tags = this.tags.sort();
      }
      if (options.noDuplicates) {
        this.tags = _.uniq(this.tags, false, function(x) {
          return x.toLowerCase();
        });
      }
      return next();
    });
  };

}).call(this);
